const express = require('express');
const exphbs = require('express-handlebars')
const path = require('path');
const logger = require('./middleware/logger')

const members = require('./Members');

const app = express();

// Handlebars middleware
app.engine('handlebars', exphbs({defaultLayout: 'main'}));
app.set('view engine', 'handlebars');

// routes / to index generated by handlebars template
app.get('/', (req, res)=>{
    res.render('index', {title: 'member app', members});
});

app.get('/about', (req, res)=>{
    res.render('about', {title: 'About'});
});

app.get('/add', (req, res)=>{
    res.render('newMember', {title: 'Add member', members});
});


//logger middleware
app.use(logger);

// Body parser middleware
app.use(express.json());
app.use(express.urlencoded({extended: false})); 

//use for static files inside folder public
//app.use(express.static(path.join(__dirname, 'public')));

app.use('/api/members', require('./routes/api/members'))


// listening to port
const port = process.env.PORT || 5000;
app.listen(port, ()=> {console.log(`app has been opened at port: ${port}`);});