### //add new member
post http://localhost:1995/api/members/registerUser
Content-Type: application/json

{
    "firstName": "Bruce",
    "lastName": "Wayne",
    "email": "jamesbond@gmail.com",
    "password": "password"
} 


### // login
post http://localhost:1995/api/members/loginUser
Content-Type: application/json

{
    "email": "death2all@gmail.com",
    "password": "password"
} 
