### //add new member
post http://localhost:5000/api/members
Content-Type: application/json

{
    "first_name": "Batman",
    "last_name": "",
    "relation": "Vigilant of Gotham"
} 

### // view all members
get http://localhost:5000/api/members


### // edit one single member detail
put http://localhost:5000/api/members/
Content-Type: application/json

{
    "first_name": "Batsy"
}

### // delete member using id
delete http://localhost:5000/api/members/3a97c8e7-9064-4456-9b27-9c52481e6e64